apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-label-controller
  namespace: kube-system
  labels:
    app: node-label-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-label-controller
  template:
    metadata:
      labels:
        app: node-label-controller
    spec:
      serviceAccountName: node-label-controller
      containers:
      - name: controller
        image: ondrejsmola/node-auto-label:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL